---
title: "Thermo Fisher raw file QC"
author: "Christian Trachsel"
date: "`r doc_date()`"
package: "`r pkg_ver('bfabricShiny')`"
abstract: >
  bla bla whatsoever.
vignette: >
  %\VignetteIndexEntry{rawfileQC}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
output: 
  BiocStyle::pdf_document
---

```{r echo=FALSE, eval=FALSE}

rawfileQC.parameter <<- list(
  mono = '/Library/Frameworks/Mono.framework/Versions/Current/bin/mono',
  exe = '/Users/cp/RiderProjects/fgcz-raw/bin/Debug/fgcz_raw.exe',
  rawfile = '/Users/cp/Downloads/20161010_04_TP_HeLa_200ng.raw'
)


```

\newpage

# Meta Data

```{r echo=FALSE, message=FALSE, warning=FALSE}

rawfileQC.parameter$progress$set(message = "read meta data", detail= "using ThermorFileReader", value = 0.1)
library(knitr)
  if (file.exists(rawfileQC.parameter$rawfile)){
      cmd <- paste(rawfileQC.parameter$mono," ", rawfileQC.parameter$exe, 
                   " ", rawfileQC.parameter$rawfile,
                   " info | grep ':' | sed -e 's/:\ /;/'",
                   sep = '')
    }else{
      cmd <- paste("ssh fgcz-r-021 '", rawfileQC.parameter$mono," ", rawfileQC.parameter$exe, 
             " ", rawfileQC.parameter$rawfile,
             " info' | grep ':' | sed -e 's/:\ /;/'",
             sep = '')
  }
message(cmd)


S <- read.csv(pipe(cmd), sep=';', 
              stringsAsFactors = FALSE, header = FALSE,
              col.names = c('attribute', 'value'))

knitr::kable(S)
```


# QC

```{r echo=FALSE, message=FALSE, warning=FALSE}
rawfileQC.parameter$progress$set(message = "read scan information", detail= "using ThermorFileReader", value = 0.3)

 if (file.exists(rawfileQC.parameter$rawfile)){
   cmd <- paste(rawfileQC.parameter$mono, 
             " ", rawfileQC.parameter$exe, 
             " ", rawfileQC.parameter$rawfile,
             " qc", 
             sep = ' ')
 }else{
cmd <- paste("ssh fgcz-r-021 '", rawfileQC.parameter$mono, 
             " ", rawfileQC.parameter$exe, 
             " ", rawfileQC.parameter$rawfile,
             " qc'", 
             sep = ' ')
}
```

## TIC versus RT

```{r echo=FALSE, message=FALSE, warning=FALSE}
QC <- read.csv(pipe(cmd), sep='\t', stringsAsFactors = FALSE, header = TRUE)

library(dplyr)
library(tidyr)
library(ggplot2)
```

```{r echo=FALSE, fig.cap='Intensity versus RT '}
rawfileQC.parameter$progress$set(message = "ploting TIC data", detail= "using ggplot2", value = 0.4)

bfabricShiny:::.TIC.BasePeak(QC)
```

## Cycle Time

```{r echo=FALSE, fig.cap='Cycle Time plot '}
bfabricShiny:::.cycle.time(QC)
```

## distribution of selected mZ values

```{r echo=FALSE, fig.cap='Time resolved distribution of selecte precursor mZ values '}
bfabricShiny:::.mz.dist(QC)
```

## Frequency of precursor charge states

```{r echo=FALSE, fig.cap='Frequency of precursor charge states'}
bfabricShiny:::.charge.states(QC)
```

# MISC

## How to reproduce this vignette
```{r eval=FALSE}

# library(parallel)
library(rmarkdown)
library(bfabricShiny)

bfabric_rawfileQC <- function(workunitid){
  S <- bfabricShiny:::getResources('cpanse', "", workunitid = workunitid)
  
  S <- mclapply(S, function(x){
    # MAIN
    rawfileQC.parameter <<- list(
      mono = 'mono',
      exe = '~cpanse/bin/fgcz_raw.exe',
      rawfile = paste("/srv/www/htdocs/", x$relativepath,sep='')
    )
    render(paste(path.package("bfabricShiny"), "/report/rawfileQC.Rmd", sep='/'),
           output_dir = '/tmp/',
           output_file = paste(basename(x$relativepath), "pdf", sep='.')
    )
  }, mc.cores = 10)
}

bfabric_rawfileQC(workunitid=158636)
```
## Session info

Here is the output of `sessionInfo()` on the system on which this
document was compiled:

```{r sessionInfo, echo=FALSE}
sessionInfo()
```


[1] New RawFileReader from Thermo Fisher Scientific  [http://planetorbitrap.com/rawfilereader#.WdOKzIqLnmG], 2017
[2] [https://github.com/cpanse/bfabricShiny]
