#R
## using fastAPI
## Christian Panse and Leonardo Schwarz
## 20251215


#=======read======
#' read function which supports pages
#' 
#' @param login bfabric login
#' @param webservicepassword bfabric webservicepassword,
#' visible when you check your user details in the bfabric system.
#' @param endpoint the endpoint, e.g., \code{'sample'}
#' @param query e,g, \code{list(containerid = 3000)}
#' @param posturl where the flask server is working
#' @param maxpages max number of supported pages to 
#' @param updateProgress a callback function for writing log output, e.g.,
#' using a \code{\link[shiny]{Progress}} object,
#' see also \url{https://shiny.rstudio.com/articles/progress.html}.
#' @param page define requested page, default is 1
#' @param posturlsuffix defines the method to use, e.g.,
#' read. also, save should work
#' @author MdE/CP 2023-03; CP 2024-12-24; LS 2025-12-15
#' @export
#' @examples
#' \dontrun{
#' bfabricShiny::read(login,
#'   webservicepassword,
#'   endpoint = 'sample',
#'   query = list('containerid' = 34777),
#'   posturl = bfabricposturl,
#'   maxitems = 1000) -> rv
#'   }
read <- function(login = NULL, webservicepassword = NULL,
                 endpoint = 'workunit',
                 offset = 0,
                 maxitems = 100,
                 query = list(),
                 posturl = NULL,
                 posturlsuffix = 'read',
                 idonly = FALSE,
                 updateProgress = NULL){
  
  stopifnot(isFALSE(is.null(login)),
            isFALSE(is.null(webservicepassword)),
            isFALSE(is.null(posturl)),
            is.numeric(offset),
            is.numeric(maxitems))
  
  # message(paste("DEBUG XXX", login, webservicepassword, posturl))
  posturl <- paste0(posturl, posturlsuffix)
  
  if (interactive()) {message(paste0("using '", posturl, "' as posturl ..."))}
  start_time <- Sys.time()
  query_result <- httr::POST(posturl,
                             body = list(login = login,
                                         webservicepassword = webservicepassword,
                                         endpoint = endpoint,
                                         query = query,
                                         idonly = idonly,
                                         page_offset = offset,
                                         page_max_results = maxitems
                             ),
                             encode = 'json')
  end_time <- Sys.time()
  
  diff_time_msg <- paste0(round(difftime(end_time, start_time, units = 'secs'), 2), " [s].")
  rv <- httr::content(query_result)
  if (is.null(rv$res)){warning("query failed."); message(rv); return(rv);}
  
  
  ## TODO(@Leo): is that possible?
  if ('errorreport' %in% names(rv$res)){
    stop(paste0("B-Fabric errorreport: ", rv$res$errorreport))
  }
  
  if (interactive()) {
    message(paste0("read query time: ", diff_time_msg))
  }
  rv
}
#R
## using fastAPI
## Christian Panse and Leonardo Schwarz
## 20251215



#=====uploadResource=======
#' Generate a workunit and upload a resource (file)  to a internal bfabric
#' storage
#'
#' @inheritParams readPages
#' @param containerid a containerid (project id or order id)
#' @param applicationid a application id
#' @param status in \code{c('AVAILABLE', 'FAILED', 'PENDING')}
#' default is 'PENDING'.
#' @param description free text, default is is empty.
#' @param inputresourceid an integer or a list of integer of inputresourceIds. 
#' Of note, this works only for  succeeding/preceding applications.
#' Default is set to \code{NULL}.
#' @param workunitname the workunit name
#' @param resourcename the reosurce name
#' @param file a filename for a file to be uploaded.
#'
#' @return returns a nested list containing the workunit and the resource
#' object returned by the save method.
#' @importFrom base64enc base64encode
#' @importFrom tools file_ext
#' @author Christian Panse <cp@fgcz.ethz.ch> 2016-2023, MdE 2023-03-17
#' @export
#' @examples
#' fRp <- file.path(Sys.getenv("HOME"), ".Rprofile")
#' source(fRp, local=TRUE)
#' tf <- tempfile()
#' write.csv(iris, file=tf)
#' rv <- bfabricShiny::uploadResource(login, webservicepassword, bfabricposturl,
#'    containerid = 3000,
#'    status = 'PENDING',
#'    description = "generated by a test run",
#'    applicationid = 212,
#'    workunitname = "bfabricShiny example",
#'    resourcename = "R's iris data",
#'    file = tf)
#'    
#' print(rv)
uploadResource <- function(login = NULL,
                           webservicepassword = NULL,
                           posturl = NULL,
                           containerid = 3000,
                           applicationid = 212,
                           status = 'PENDING',
                           description = '',
                           inputresourceid = NULL,
                           workunitname = 'bfabricShiny result',
                           resourcename = 'bfabricShiny report',
                           file = NULL) {
  
  stopifnot(isFALSE(is.null(login)),
            isFALSE(is.null(webservicepassword)),
            isFALSE(is.null(file)),
            isFALSE(is.null(posturl)),
            file.exists(file)
  )
  
  stopifnot(status %in% c('AVAILABLE', 'FAILED', 'PENDING'))
  
  fileContent <- readBin(file, "raw", file.info(file)[1, "size"]) |>
    base64enc::base64encode(tools::file_ext(file))
  
  description <- 
    sprintf("%s\n\n
Generated by Rpkg https://github.com/fgcz/bfabricShiny/ version %s.
System information: %s\n
To help us funding further development, please cite:
(bfabricSiny) PMID: 36073980 DOI: 10.1515/jib-2022-0031",
            description,
            packageVersion('bfabricShiny'),
            paste(Sys.info(), collapse = ', '))
  
  wu <-
    .createWorkunit(
      login = login,
      webservicepassword = webservicepassword,
      posturl = posturl,
      containerid = containerid,
      inputresourceid = inputresourceid,
      applicationid = applicationid,
      name = workunitname,
      status = status,
      description = description
    )
  
  #res <- 
  #  .saveResource(login, webservicepassword,
  #                   posturl = posturl,
  #                   workunitid = wu[[1]]$id,
  #                   content = fileContent,
  #                   name = resourcename
  #
  workunitid <- wu$res[[1]]$id
  res <- save(login, webservicepassword,
              posturl = posturl,
              endpoint = 'resource',
              query = list(
                'name' = sprintf("WU%s-%s-%s",workunitid,
                                 format(Sys.time(), format="%Y%m%d-%H%M"), resourcename),
                'workunitid' = workunitid,
                'base64' = fileContent
              )
              
  )
  
  list(workunit = wu, resource = res)
}
