# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
#
# See https://github.com/r-lib/actions/tree/master/examples#readme for
# additional example workflows available for the R community.

name: R-CMD-check-bfabricShiny
env:
    ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
on:
  push:
    branches: [ bfabric10_c ]
  pull_request:
    branches: [ bfabric10_c ]

jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        r-version: [4.1.0]
    steps:
      - uses: actions/checkout@v2
      - name: Set up R ${{ matrix.r-version }}
        uses: r-lib/actions/setup-r@v1
        with:
          r-version: ${{ matrix.r-version }}
      - name: Install some Debian packages
        run: sudo apt-get install -y  curl
      - name: Install dependencies
        run: |
          pkgs <- c('testthat', 'knitr', 'shiny', 'protViz', 'roxygen2', 'rcmdcheck', 'rmarkdown', 'devtools', 'PKI', 'devtools')
          pkgs[!pkgs %in% installed.packages()] |> install.packages()
          remotes::install_deps(dependencies = TRUE);  devtools::install_github('trestletech/shinyStore', force = TRUE, type='source');
        shell: Rscript {0}
      - name: Check
        run: rcmdcheck::rcmdcheck(build_args = "", args = "", error_on = "error", check_dir = "/tmp/bfabricShiny.Rcheck")
        shell: Rscript {0}
      - uses: actions/upload-artifact@v2
        with:
            name: bfabricShiny.Rcheck
            path: /tmp/bfabricShiny.Rcheck
            if-no-files-found: warn
